openapi: 3.0.0
info:
  title: Task Management API
  description: API documentation for managing tasks using a RESTful interface.
  version: 1.0.0
  contact:
    name: Manuel Paniagua
    email: your-email@example.com

servers:
  - url: http://localhost:3000
    description: Development server

tags:
  - name: Authorization
    description: Endpoints related to user authorization (register, login, logout, profile)
  - name: Task Management
    description: Endpoints related to managing tasks

paths:
  /register:
    post:
      tags:
        - Authorization
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username of the new user
                email:
                  type: string
                  description: The email of the new user
                password:
                  type: string
                  description: The password of the new user
              required:
                - username
                - email
                - password
      responses:
        '200':
          description: The registered user
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The unique identifier of the user
                  email:
                    type: string
                    description: The email of the user
                  username:
                    type: string
                    description: The username of the user

  /login:
    post:
      tags:
        - Authorization
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The email of the user
                password:
                  type: string
                  description: The password of the user
              required:
                - email
                - password
      responses:
        '200':
          description: The logged-in user
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The unique identifier of the user
                  email:
                    type: string
                    description: The email of the user
                  username:
                    type: string
                    description: The username of the user

  /logout:
    post:
      tags:
        - Authorization
      summary: Logout a user
      responses:
        '200':
          description: User logged out successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The logout message

  /profile:
    get:
      tags:
        - Authorization
      summary: Get the profile of the logged-in user
      responses:
        '200':
          description: The profile of the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The unique identifier of the user
                  email:
                    type: string
                    description: The email of the user
                  username:
                    type: string
                    description: The username of the user
        '400':
          description: User not found

  /task:
    get:
      tags:
        - Task Management
      summary: Get all tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: The unique identifier of the task
                    name:
                      type: string
                      description: The name of the task
                    description:
                      type: string
                      description: The description of the task

    post:
      tags:
        - Task Management
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the task
                description:
                  type: string
                  description: The description of the task
              required:
                - name
                - description
      responses:
        '200':
          description: The created task
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The unique identifier of the task
                  name:
                    type: string
                    description: The name of the task
                  description:
                    type: string
                    description: The description of the task

  /task/{id}:
    get:
      tags:
        - Task Management
      summary: Get a task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the task to retrieve
      responses:
        '200':
          description: The task with the specified ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The unique identifier of the task
                  name:
                    type: string
                    description: The name of the task
                  description:
                    type: string
                    description: The description of the task
        '404':
          description: Task not found

    put:
      tags:
        - Task Management
      summary: Update a task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the task to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The new name of the task
                description:
                  type: string
                  description: The new description of the task
              required:
                - name
                - description
      responses:
        '200':
          description: The updated task
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The unique identifier of the task
                  name:
                    type: string
                    description: The updated name of the task
                  description:
                    type: string
                    description: The updated description of the task
        '404':
          description: Task not found

    delete:
      tags:
        - Task Management
      summary: Delete a task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the task to delete
      responses:
        '200':
          description: The deleted task
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The unique identifier of the deleted task
                  name:
                    type: string
                    description: The name of the deleted task
                  description:
                    type: string
                    description: The description of the deleted task
        '404':
          description: Task not found

  /task/count:
    get:
      tags:
        - Task Management
      summary: Get the total count of tasks
      responses:
        '200':
          description: The total number of tasks
          content:
            application/json:
              schema:
                type: integer
                example: 5  
